services:
  realtimedb:
    image: "postgres"

  zookeeper:
    image: confluentinc/cp-zookeeper
  
  kafka:
    image: confluentinc/cp-kafka

  # cache:
  #   image: "redis"

  realtime.socket:
    image: realtime_socket_image
    build:
      context: src/backend/realtime-socket
      dockerfile: ./Dockerfile

  realtime.ui:
    image: realtime_ui
    build:
      context: src/frontend/realtime-app-ui
      dockerfile: ./Dockerfile

  # realtime.api:
  #   image: realtime_api_image
  #   build:
  #     context: src/backend/realtime-api
  #     dockerfile: ./Dockerfile