version: '3'

services:
  db:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
#  cache:
#    image: "redis"
#    ports:
#      - "6379:6379"
#    environment:
#      - ALLOW_EMPTY_PASSWORD=yes
#      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
  # app:
  #   build: .
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     SPRING_PROFILE_ACTIVE: dev
  #     SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/postgres"
  #     SPRING_REDIS_HOST: cache
  #     SPRING_REDIS_PORT: 6379
  #   depends_on:
  #     - db
  #     - cache