spring:
  profiles:
    active: ${ENV_ACTIVE_PROFILE:dev}
    include:
      - common
      - db
      - jwt
      - logging
      - smtp
      - kafka
      - redis
  application:
    name: realtime-app