spring:
  mail:
    host: smtp.gmail.com
    port: 465
    protocol: smtps
    username: ${SMTP_USER:b.calisgan.19@gmail.com}
    password: ${SMTP_PASSWORD:password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com